# Data Analysis

In this notebook, I'd like to finally get down to analyzing the sentiment of these tweets. We'll need to conduct the analysis, store the result in a new column of the dataframe, and then visualize it somehow to get an understanding of what's going on. Let's get started!

**Hypothesis:** Tweets about Naomi Osaka will be overwhelmingly more positive than tweets about Serena Williams.

In [15]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd

from statistics import mean
from textblob import TextBlob

In [71]:
filepath = "./data/CLEANED_naomi-serena.pkl"

In [72]:
data = pd.read_pickle(filepath)

In [73]:
data.head()

,tweet_date,tweet_text,search query
0,Sat Sep 08 19:59:59 +0000 2018,"[naomi, osaka, upset, serena, williams, contro...",naomi osaka
1,Sat Sep 08 19:59:57 +0000 2018,"[go, girl, got, back, congrats, open]",naomi osaka
2,Sat Sep 08 19:59:56 +0000 2018,"[probably, felt, like, friend, house, mom, sta...",naomi osaka
3,Sat Sep 08 19:59:55 +0000 2018,"[congrats, girly, let, anyone, take, moment, o...",naomi osaka
4,Sat Sep 08 19:59:55 +0000 2018,"[naomi, osaka, defeat, serena, williams, drama...",naomi osaka

In [7]:
test_data = data[:10].copy()
test_data

,tweet_date,tweet_text,search query
0,Sat Sep 08 19:59:59 +0000 2018,"[naomi, osaka, upset, serena, williams, contro...",naomi osaka
1,Sat Sep 08 19:59:57 +0000 2018,"[go, girl, got, back, congrats, open]",naomi osaka
2,Sat Sep 08 19:59:56 +0000 2018,"[probably, felt, like, friend, house, mom, sta...",naomi osaka
3,Sat Sep 08 19:59:55 +0000 2018,"[congrats, girly, let, anyone, take, moment, o...",naomi osaka
4,Sat Sep 08 19:59:55 +0000 2018,"[naomi, osaka, defeat, serena, williams, drama...",naomi osaka
6,Sat Sep 08 19:59:54 +0000 2018,"[carlos, ramos, also, robbed, osaka, imagine, ...",naomi osaka
7,Sat Sep 08 19:59:52 +0000 2018,"[yes, bravo, bajin, course, love, always, sinc...",naomi osaka
8,Sat Sep 08 19:59:50 +0000 2018,"[tennis, official, coach, seen, coaching, play...",naomi osaka
9,Sat Sep 08 19:59:50 +0000 2018,"[naomi, osaka, top, serena, williams, open, fi...",naomi osaka
10,Sat Sep 08 19:59:49 +0000 2018,"[booing, damn, naomi, osaka, girl, cooking, go...",naomi osaka

In [10]:
for tweet in test_data['tweet_text']:
    for word in tweet:
        print(TextBlob(word).sentiment)

Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.55, subjectivity=0.95)
Sentiment(polarity=0.0, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=1.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=-0.4333333333333333, subjectivity=0.6)
Sentiment(polarity=0.0, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=1.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.2, subjectivity=0.2)
Sentiment(polarity=0.5, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=-0.4, subjectivity=0.4)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.5, subjectivity=0.6)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.5, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.1, subjectivity=0.1)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.5, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.5)
Sentiment(polarity=0.0, subjectivity=1.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.25, subjectivity=0.3333333333333333)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.5, subjectivity=1.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=-0.07142857142857142, subjectivity=0.21428571428571427)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.7, subjectivity=0.6000000000000001)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.4, subjectivity=0.7)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.0, subjectivity=0.0)

This is pretty interesting. It looks like most words are neutral and don't mean anything. What I'd like to do is two analyses of sentiment:

1. Get the sentiment of each word, average them to get the total sentiment of those words
2. Combine the words into a pseudo-sentence and get the average sentiment of the sentence

## Strategy 1: Word-Based Sentiment

In [40]:
def get_sentiment(tweets):
    
    for tweet in tweets:
        sentiments = []
        for word in tweet:
            sentiments.append(TextBlob(word).sentiment.polarity)
        return mean(sentiments)

In [41]:
get_sentiment(test_data['tweet_text'])

0.05500000000000001

In analyzing this output, I'm not sure I like what I'm seeing. Tweets that are clearly positive in nature are registering as neutral, and tweets that couldn't be considered negative have a score above zero. Let's see if the sentence-based method has any different output.

In [22]:
def get_sentiment_2(tweets):
    
    for tweet in tweets:
        sentiments = []
        sentence = " ".join(tweet)
        print(sentence, TextBlob(sentence).sentiment.polarity)

In [23]:
get_sentiment_2(test_data['tweet_text'])

naomi osaka upset serena williams controversial open final cnn smartnews 0.18333333333333335
go girl got back congrats open 0.0
probably felt like friend house mom started yelling usopen 0.0
congrats girly let anyone take moment outplayed everyone even goat serena 0.0
naomi osaka defeat serena williams dramatic open final -0.14444444444444443
carlos ramos also robbed osaka imagine much better would feel broke serena go instead giving game 0.04999999999999999
yes bravo bajin course love always since turned pro 0.5
tennis official coach seen coaching player issue warning coach called ejected better yet get rid coaching signal rule altogether player helpless effect coach action mid match 0.19999999999999998
naomi osaka top serena williams open final becomes first japanese grand slam single champion japan time 0.1683673469387755
booing damn naomi osaka girl cooking good job spot light earned naomi 0.55

A bit better, but I'm starting to think that it was a mistake tokenizing the words the way I did. Let's see if I can perform the sentiment on these tweets with no tokenization.

In [24]:
test_file = pd.read_pickle("./data/DATA00_naomi-serena-all.pkl")

In [25]:
test_file.head()

,tweet_date,tweet_text,search query
0,Sat Sep 08 19:59:59 +0000 2018,Naomi Osaka upsets Serena Williams in controve...,naomi osaka
1,Sat Sep 08 19:59:57 +0000 2018,"@ Naomi_Osaka_ , you go girl! I got your back!...",naomi osaka
2,Sat Sep 08 19:59:56 +0000 2018,@ Naomi_Osaka_ probably felt like she was at h...,naomi osaka
3,Sat Sep 08 19:59:55 +0000 2018,"Congrats girly, don’t let anyone take this mom...",naomi osaka
4,Sat Sep 08 19:59:55 +0000 2018,Naomi Osaka defeats Serena Williams in a drama...,naomi osaka

In [26]:
test2 = test_file[:10].copy()

In [27]:
test2

,tweet_date,tweet_text,search query
0,Sat Sep 08 19:59:59 +0000 2018,Naomi Osaka upsets Serena Williams in controve...,naomi osaka
1,Sat Sep 08 19:59:57 +0000 2018,"@ Naomi_Osaka_ , you go girl! I got your back!...",naomi osaka
2,Sat Sep 08 19:59:56 +0000 2018,@ Naomi_Osaka_ probably felt like she was at h...,naomi osaka
3,Sat Sep 08 19:59:55 +0000 2018,"Congrats girly, don’t let anyone take this mom...",naomi osaka
4,Sat Sep 08 19:59:55 +0000 2018,Naomi Osaka defeats Serena Williams in a drama...,naomi osaka
5,Sat Sep 08 19:59:55 +0000 2018,https://twitter.com/juventino5555/status/10377...,naomi osaka
6,Sat Sep 08 19:59:54 +0000 2018,Carlos Ramos also robbed Osaka. Imagine how mu...,naomi osaka
7,Sat Sep 08 19:59:52 +0000 2018,Yes Bravo to @ BigSascha Bajin And of course l...,naomi osaka
8,Sat Sep 08 19:59:50 +0000 2018,Tennis officials.. where coaches are seen coac...,naomi osaka
9,Sat Sep 08 19:59:50 +0000 2018,Naomi Osaka tops Serena Williams in U.S. Open ...,naomi osaka

In [28]:
for tweet in test2['tweet_text']:
    print(tweet, TextBlob(tweet).sentiment.polarity)

Naomi Osaka upsets Serena Williams in controversial US Open final - CNN # SmartNewshttps://edition.cnn.com/2018/09/08/sport/naomi-osaka-serena-williams-us-open-tennis-int-spt/index.html … 0.18333333333333335
@ Naomi_Osaka_ , you go girl! I got your back! Congrats on the US open! 0.0
@ Naomi_Osaka_ probably felt like she was at her friend’s house when their mom started yelling at them # usopen 0.0
Congrats girly, don’t let anyone take this moment from you..you outplayed everyone, even the GOAT Serena @ Naomi_Osaka_ 0.0
Naomi Osaka defeats Serena Williams in a dramatic US Open final https://twitter.com/i/events/1038540032330493952 … -0.14444444444444443
https://twitter.com/juventino5555/status/1037768949109276672?s=19 … 0.0
Carlos Ramos also robbed Osaka. Imagine how much better she would feel if she broke Serena to go up 5-3 instead of being giving the game. 0.04999999999999999
Yes Bravo to @ BigSascha Bajin And of course love as always (since she turned pro!) to @ Naomi_Osaka_ https://twitter.com/bgtennisnation/status/1038563742961881090 … 0.625
Tennis officials.. where coaches are seen coaching their player.. why not issue a warning to the coach.. and if he is called on it again, he is ejected. Better yet.. get rid of the coaching signals rule altogether..A player is helpless to effect their coach’s actions mid match. 0.25
Naomi Osaka tops Serena Williams in U.S. Open final, becomes first Japanese grand slam singles champion | The Japan Times https://www.japantimes.co.jp/sports/2018/09/09/more-sports/tennis/naomi-osaka-tops-serena-williams-u-s-open-final-becomes-first-japanese-grand-slam-singles-champion/#.W5Ric76cSlQ.twitter … 0.15

These still seem overwhelmingly positive, though I'm getting more sentiment than from the tokenized corpus alone. Just to test the hypothesis, let's see what happens with the last 10 tweets of the dataset.

In [29]:
test3 = test_file[-10:].copy()

In [30]:
test3

,tweet_date,tweet_text,search query
23818,Sat Sep 08 18:45:26 +0000 2018,You should see what Serena's coach has just ad...,serena williams
23819,Sat Sep 08 18:45:25 +0000 2018,Serena Williams. The greatest athlete of all t...,serena williams
23820,Sat Sep 08 18:45:25 +0000 2018,Congrats to # naomiosaka who just won the # US...,serena williams
23821,Sat Sep 08 18:45:25 +0000 2018,Justified as in being upset at a stupid rule/v...,serena williams
23822,Sat Sep 08 18:45:25 +0000 2018,That's why you're so irrelevant Mr. Kasich. Ca...,serena williams
23823,Sat Sep 08 18:45:25 +0000 2018,@ serenawilliams you are an inspiration and a ...,serena williams
23824,Sat Sep 08 18:45:24 +0000 2018,@ serenawilliams I love you so much mommy. I k...,serena williams
23825,Sat Sep 08 18:45:24 +0000 2018,@ serenawilliams Mama needs a dictionary. Grac...,serena williams
23826,Sat Sep 08 18:45:23 +0000 2018,I’d rather lose than cheat @ serenawilliams,serena williams
23827,Sat Sep 08 18:45:23 +0000 2018,"Sorry, don't agree on this one. Referee had no...",serena williams

In [31]:
for tweet in test3['tweet_text']:
    print(tweet, TextBlob(tweet).sentiment.polarity)

You should see what Serena's coach has just admitted to. Yep, coaching his player. 0.0
Serena Williams. The greatest athlete of all time. A black woman. # USOpen18 0.4166666666666667
Congrats to # naomiosaka who just won the # USopen against her idol, # SerenaWilliams https://www.instagram.com/p/Bne3yDrBRn3/?utm_source=ig_twitter_share&igshid=755i1rx1ff4k … 0.0
Justified as in being upset at a stupid rule/violation. -0.19999999999999996
That's why you're so irrelevant Mr. Kasich. Calling an umpire names and a thief is not being a real sport and a class act. -0.15
@ serenawilliams you are an inspiration and a role model for women. Not only in sports but ALL women. # UsOpenFinal 0.0
@ serenawilliams I love you so much mommy. I know that you were right. You are amazing woman and I want to be like you. I will never ever stop dreaming to see you. And of course congratulations @ Naomi_Osaka_. Don't be sad. You are amazing. You don't deserve that, but life happenspic.twitter.com/PMWFTayrqH 0.280952380952381
@ serenawilliams Mama needs a dictionary. Gracious? Humble? Ummm, OK. And remember, what you think is right is just your opinion. 0.1952380952380952
I’d rather lose than cheat @ serenawilliams 0.0
Sorry, don't agree on this one. Referee had no business making a baseless accusation and taking a point. It was unjust & wrong. It set @ serenawilliams off & they knew it would. This will take away from Osaka's win. An idiot referee wanting to be the star. -0.25

Still not quite what I was expecting, but the sentiment is there, nonetheless.

Let's do a side-by-side comparison of them both, with just the tokenized sentences.

In [48]:
test_data['lexicon-based sentiment'] = test_data['tweet_text'].apply(lambda x: mean([TextBlob(word).sentiment.polarity for word in x]))

In [49]:
test_data

,tweet_date,tweet_text,search query,lexicon-based sentiment
0,Sat Sep 08 19:59:59 +0000 2018,"[naomi, osaka, upset, serena, williams, contro...",naomi osaka,0.055000
1,Sat Sep 08 19:59:57 +0000 2018,"[go, girl, got, back, congrats, open]",naomi osaka,0.000000
2,Sat Sep 08 19:59:56 +0000 2018,"[probably, felt, like, friend, house, mom, sta...",naomi osaka,0.000000
3,Sat Sep 08 19:59:55 +0000 2018,"[congrats, girly, let, anyone, take, moment, o...",naomi osaka,0.000000
4,Sat Sep 08 19:59:55 +0000 2018,"[naomi, osaka, defeat, serena, williams, drama...",naomi osaka,-0.054167
6,Sat Sep 08 19:59:54 +0000 2018,"[carlos, ramos, also, robbed, osaka, imagine, ...",naomi osaka,0.018750
7,Sat Sep 08 19:59:52 +0000 2018,"[yes, bravo, bajin, course, love, always, sinc...",naomi osaka,0.055556
8,Sat Sep 08 19:59:50 +0000 2018,"[tennis, official, coach, seen, coaching, play...",naomi osaka,0.023077
9,Sat Sep 08 19:59:50 +0000 2018,"[naomi, osaka, top, serena, williams, open, fi...",naomi osaka,0.073661
10,Sat Sep 08 19:59:49 +0000 2018,"[booing, damn, naomi, osaka, girl, cooking, go...",naomi osaka,0.091667

In [50]:
test_data['pseudo-sentence sentiment'] = test_data['tweet_text'].apply(lambda x: TextBlob(" ".join(x)).sentiment.polarity)

In [51]:
test_data

,tweet_date,tweet_text,search query,lexicon-based sentiment,pseudo-sentence sentiment
0,Sat Sep 08 19:59:59 +0000 2018,"[naomi, osaka, upset, serena, williams, contro...",naomi osaka,0.055000,0.183333
1,Sat Sep 08 19:59:57 +0000 2018,"[go, girl, got, back, congrats, open]",naomi osaka,0.000000,0.000000
2,Sat Sep 08 19:59:56 +0000 2018,"[probably, felt, like, friend, house, mom, sta...",naomi osaka,0.000000,0.000000
3,Sat Sep 08 19:59:55 +0000 2018,"[congrats, girly, let, anyone, take, moment, o...",naomi osaka,0.000000,0.000000
4,Sat Sep 08 19:59:55 +0000 2018,"[naomi, osaka, defeat, serena, williams, drama...",naomi osaka,-0.054167,-0.144444
6,Sat Sep 08 19:59:54 +0000 2018,"[carlos, ramos, also, robbed, osaka, imagine, ...",naomi osaka,0.018750,0.050000
7,Sat Sep 08 19:59:52 +0000 2018,"[yes, bravo, bajin, course, love, always, sinc...",naomi osaka,0.055556,0.500000
8,Sat Sep 08 19:59:50 +0000 2018,"[tennis, official, coach, seen, coaching, play...",naomi osaka,0.023077,0.200000
9,Sat Sep 08 19:59:50 +0000 2018,"[naomi, osaka, top, serena, williams, open, fi...",naomi osaka,0.073661,0.168367
10,Sat Sep 08 19:59:49 +0000 2018,"[booing, damn, naomi, osaka, girl, cooking, go...",naomi osaka,0.091667,0.550000

It looks like the pseudo-sentence sentiment is stronger, with a significant difference in polarity. I think it might be beneficial to retain a tokenized and non-tokenized version of the tweet, to compare those sentiment polarities as well.

In [52]:
%run scrub_tweets.py

Filename: DATA00_naomi-serena-all.pkl
Loading ./data/DATA00_naomi-serena-all.pkl...
A brief look at the data...
                       tweet_date  \
0  Sat Sep 08 19:59:59 +0000 2018
1  Sat Sep 08 19:59:57 +0000 2018
2  Sat Sep 08 19:59:56 +0000 2018
3  Sat Sep 08 19:59:55 +0000 2018
4  Sat Sep 08 19:59:55 +0000 2018

                                          tweet_text search query
0  Naomi Osaka upsets Serena Williams in controve...  naomi osaka
1  @ Naomi_Osaka_ , you go girl! I got your back!...  naomi osaka
2  @ Naomi_Osaka_ probably felt like she was at h...  naomi osaka
3  Congrats girly, don’t let anyone take this mom...  naomi osaka
4  Naomi Osaka defeats Serena Williams in a drama...  naomi osaka
---------------------------
                           tweet_date  \
23823  Sat Sep 08 18:45:25 +0000 2018
23824  Sat Sep 08 18:45:24 +0000 2018
23825  Sat Sep 08 18:45:24 +0000 2018
23826  Sat Sep 08 18:45:23 +0000 2018
23827  Sat Sep 08 18:45:23 +0000 2018

                                              tweet_text     search query
23823  @ serenawilliams you are an inspiration and a ...  serena williams
23824  @ serenawilliams I love you so much mommy. I k...  serena williams
23825  @ serenawilliams Mama needs a dictionary. Grac...  serena williams
23826        I’d rather lose than cheat @ serenawilliams  serena williams
23827  Sorry, don't agree on this one. Referee had no...  serena williams
Step 1: Removing noise...
Done.
                       tweet_date  \
0  Sat Sep 08 19:59:59 +0000 2018
1  Sat Sep 08 19:59:57 +0000 2018
2  Sat Sep 08 19:59:56 +0000 2018
3  Sat Sep 08 19:59:55 +0000 2018
4  Sat Sep 08 19:59:55 +0000 2018

                                          tweet_text search query
0  Naomi Osaka upsets Serena Williams in controve...  naomi osaka
1    , you go girl! I got your back! Congrats on ...  naomi osaka
2    probably felt like she was at her friend’s h...  naomi osaka
3  Congrats girly, don’t let anyone take this mom...  naomi osaka
4  Naomi Osaka defeats Serena Williams in a drama...  naomi osaka
Step 2: Normalizing text...
Done.
                       tweet_date  \
0  Sat Sep 08 19:59:59 +0000 2018
1  Sat Sep 08 19:59:57 +0000 2018
2  Sat Sep 08 19:59:56 +0000 2018
3  Sat Sep 08 19:59:55 +0000 2018
4  Sat Sep 08 19:59:55 +0000 2018

                                          tweet_text search query
0  naomi osaka upsets serena williams in controve...  naomi osaka
1      you go girl  i got your back  congrats on ...  naomi osaka
2    probably felt like she was at her friends ho...  naomi osaka
3  congrats girly  do not let anyone take this mo...  naomi osaka
4  naomi osaka defeats serena williams in a drama...  naomi osaka
Step 3: Preprocessing text...
Done.
Your cleaned data:
                       tweet_date  \
0  Sat Sep 08 19:59:59 +0000 2018
1  Sat Sep 08 19:59:57 +0000 2018
2  Sat Sep 08 19:59:56 +0000 2018
3  Sat Sep 08 19:59:55 +0000 2018
4  Sat Sep 08 19:59:55 +0000 2018

                                          tweet_text search query  \
0  naomi osaka upsets serena williams in controve...  naomi osaka
1      you go girl  i got your back  congrats on ...  naomi osaka
2    probably felt like she was at her friends ho...  naomi osaka
3  congrats girly  do not let anyone take this mo...  naomi osaka
4  naomi osaka defeats serena williams in a drama...  naomi osaka

                                     processed_tweet
0  [naomi, osaka, upset, serena, williams, contro...
1              [go, girl, got, back, congrats, open]
2  [probably, felt, like, friend, house, mom, sta...
3  [congrats, girly, let, anyone, take, moment, o...
4  [naomi, osaka, defeat, serena, williams, drama...
---------------------------
                           tweet_date  \
23823  Sat Sep 08 18:45:25 +0000 2018
23824  Sat Sep 08 18:45:24 +0000 2018
23825  Sat Sep 08 18:45:24 +0000 2018
23826  Sat Sep 08 18:45:23 +0000 2018
23827  Sat Sep 08 18:45:23 +0000 2018

                                              tweet_text     search query  \
23823    you are an inspiration and a role model for ...  serena williams
23824    i love you so much mommy  i know that you we...  serena williams
23825    mama needs a dictionary  gracious  humble  u...  serena williams
23826                   i would rather lose than cheat    serena williams
23827  sorry  do not agree on this one  referee had n...  serena williams

                                         processed_tweet
23823  [inspiration, role, model, woman, sport, woman...
23824  [love, much, mommy, know, right, amazing, woma...
23825  [mama, need, dictionary, gracious, humble, umm...
23826                       [would, rather, lose, cheat]
23827  [sorry, agree, one, referee, business, making,...
Save file as: DATA02_naomi-serena-processed.pkl
Saving ./data/CLEANED_DATA02_naomi-serena-processed.pkl...
Done. End.

In [53]:
new_data = pd.read_pickle("./data/CLEANED_DATA02_naomi-serena-processed.pkl")

In [54]:
new_data.head()

,tweet_date,tweet_text,search query,processed_tweet
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro..."
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]"
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta..."
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o..."
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama..."

In [55]:
new_test_data = new_data[:10].copy()

In [56]:
new_test_data['tweet sentiment'] = new_test_data['tweet_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
new_test_data['tokenized sentiment'] = new_test_data['processed_tweet'].apply(lambda x: mean([TextBlob(word).sentiment.polarity for word in x]))

In [57]:
new_test_data

,tweet_date,tweet_text,search query,processed_tweet,tweet sentiment,tokenized sentiment
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro...",0.183333,0.055000
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]",0.000000,0.000000
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta...",0.000000,0.000000
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o...",0.000000,0.000000
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama...",-0.144444,-0.054167
6,Sat Sep 08 19:59:54 +0000 2018,carlos ramos also robbed osaka imagine how mu...,naomi osaka,"[carlos, ramos, also, robbed, osaka, imagine, ...",0.050000,0.018750
7,Sat Sep 08 19:59:52 +0000 2018,yes bravo to bajin and of course love as alw...,naomi osaka,"[yes, bravo, bajin, course, love, always, sinc...",0.500000,0.055556
8,Sat Sep 08 19:59:50 +0000 2018,tennis officials where coaches are seen coac...,naomi osaka,"[tennis, official, coach, seen, coaching, play...",0.250000,0.023077
9,Sat Sep 08 19:59:50 +0000 2018,naomi osaka tops serena williams in u s open ...,naomi osaka,"[naomi, osaka, top, serena, williams, open, fi...",0.150000,0.073661
10,Sat Sep 08 19:59:49 +0000 2018,booing damn naomi osaka won the girl was cooki...,naomi osaka,"[booing, damn, naomi, osaka, girl, cooking, go...",0.550000,0.091667

In [60]:
new_test_data.rename(index=str, columns={"tweet_text": "original tweet", "processed_tweet": "tweet_text"})

,tweet_date,original tweet,search query,tweet_text,tweet sentiment,tokenized sentiment
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro...",0.183333,0.055000
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]",0.000000,0.000000
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta...",0.000000,0.000000
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o...",0.000000,0.000000
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama...",-0.144444,-0.054167
6,Sat Sep 08 19:59:54 +0000 2018,carlos ramos also robbed osaka imagine how mu...,naomi osaka,"[carlos, ramos, also, robbed, osaka, imagine, ...",0.050000,0.018750
7,Sat Sep 08 19:59:52 +0000 2018,yes bravo to bajin and of course love as alw...,naomi osaka,"[yes, bravo, bajin, course, love, always, sinc...",0.500000,0.055556
8,Sat Sep 08 19:59:50 +0000 2018,tennis officials where coaches are seen coac...,naomi osaka,"[tennis, official, coach, seen, coaching, play...",0.250000,0.023077
9,Sat Sep 08 19:59:50 +0000 2018,naomi osaka tops serena williams in u s open ...,naomi osaka,"[naomi, osaka, top, serena, williams, open, fi...",0.150000,0.073661
10,Sat Sep 08 19:59:49 +0000 2018,booing damn naomi osaka won the girl was cooki...,naomi osaka,"[booing, damn, naomi, osaka, girl, cooking, go...",0.550000,0.091667

In [64]:
earlier_results = test_data[["lexicon-based sentiment", "pseudo-sentence sentiment"]]

In [69]:
new_test_data.join(earlier_results)

,tweet_date,tweet_text,search query,processed_tweet,tweet sentiment,tokenized sentiment,lexicon-based sentiment,pseudo-sentence sentiment
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro...",0.183333,0.055000,0.055000,0.183333
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]",0.000000,0.000000,0.000000,0.000000
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta...",0.000000,0.000000,0.000000,0.000000
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o...",0.000000,0.000000,0.000000,0.000000
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama...",-0.144444,-0.054167,-0.054167,-0.144444
6,Sat Sep 08 19:59:54 +0000 2018,carlos ramos also robbed osaka imagine how mu...,naomi osaka,"[carlos, ramos, also, robbed, osaka, imagine, ...",0.050000,0.018750,0.018750,0.050000
7,Sat Sep 08 19:59:52 +0000 2018,yes bravo to bajin and of course love as alw...,naomi osaka,"[yes, bravo, bajin, course, love, always, sinc...",0.500000,0.055556,0.055556,0.500000
8,Sat Sep 08 19:59:50 +0000 2018,tennis officials where coaches are seen coac...,naomi osaka,"[tennis, official, coach, seen, coaching, play...",0.250000,0.023077,0.023077,0.200000
9,Sat Sep 08 19:59:50 +0000 2018,naomi osaka tops serena williams in u s open ...,naomi osaka,"[naomi, osaka, top, serena, williams, open, fi...",0.150000,0.073661,0.073661,0.168367
10,Sat Sep 08 19:59:49 +0000 2018,booing damn naomi osaka won the girl was cooki...,naomi osaka,"[booing, damn, naomi, osaka, girl, cooking, go...",0.550000,0.091667,0.091667,0.550000

The results are almost exactly the same: a pseudo-sentence made by concatenating the tokenized words produced much the same sentiment as the tweet itself. Indeed, removing stop words and the like seems to have no impact on the overall sentiment of the tweet. However, analyzing the sentiment by averaging the tokenized words individually seems much less useful than analyzing the sentence as a whole (I believe due to the nature of syntax and semantics on a sentence vs. word level).

Analysis will proceed as follows: by joining the tokenized words into a longer string, and calculating the overall sentiment of the entire phrase.

### Calculating Sentiment for Data:

In [82]:
new_data.head()

,tweet_date,tweet_text,search query,processed_tweet
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro..."
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]"
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta..."
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o..."
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama..."

In [83]:
analyzed_tweets = new_data.copy()

In [84]:
analyzed_tweets.head()

,tweet_date,tweet_text,search query,processed_tweet
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro..."
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]"
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta..."
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o..."
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama..."

In [85]:
analyzed_tweets.tail()

,tweet_date,tweet_text,search query,processed_tweet
23823,Sat Sep 08 18:45:25 +0000 2018,you are an inspiration and a role model for ...,serena williams,"[inspiration, role, model, woman, sport, woman..."
23824,Sat Sep 08 18:45:24 +0000 2018,i love you so much mommy i know that you we...,serena williams,"[love, much, mommy, know, right, amazing, woma..."
23825,Sat Sep 08 18:45:24 +0000 2018,mama needs a dictionary gracious humble u...,serena williams,"[mama, need, dictionary, gracious, humble, umm..."
23826,Sat Sep 08 18:45:23 +0000 2018,i would rather lose than cheat,serena williams,"[would, rather, lose, cheat]"
23827,Sat Sep 08 18:45:23 +0000 2018,sorry do not agree on this one referee had n...,serena williams,"[sorry, agree, one, referee, business, making,..."

In [86]:
analyzed_tweets['sentiment'] = analyzed_tweets['processed_tweet'].apply(lambda x: TextBlob(" ".join(x)).sentiment.polarity)

In [87]:
analyzed_tweets.head()

,tweet_date,tweet_text,search query,processed_tweet,sentiment
0,Sat Sep 08 19:59:59 +0000 2018,naomi osaka upsets serena williams in controve...,naomi osaka,"[naomi, osaka, upset, serena, williams, contro...",0.183333
1,Sat Sep 08 19:59:57 +0000 2018,you go girl i got your back congrats on ...,naomi osaka,"[go, girl, got, back, congrats, open]",0.000000
2,Sat Sep 08 19:59:56 +0000 2018,probably felt like she was at her friends ho...,naomi osaka,"[probably, felt, like, friend, house, mom, sta...",0.000000
3,Sat Sep 08 19:59:55 +0000 2018,congrats girly do not let anyone take this mo...,naomi osaka,"[congrats, girly, let, anyone, take, moment, o...",0.000000
4,Sat Sep 08 19:59:55 +0000 2018,naomi osaka defeats serena williams in a drama...,naomi osaka,"[naomi, osaka, defeat, serena, williams, drama...",-0.144444

In [88]:
analyzed_tweets.tail()

,tweet_date,tweet_text,search query,processed_tweet,sentiment
23823,Sat Sep 08 18:45:25 +0000 2018,you are an inspiration and a role model for ...,serena williams,"[inspiration, role, model, woman, sport, woman...",0.000000
23824,Sat Sep 08 18:45:24 +0000 2018,i love you so much mommy i know that you we...,serena williams,"[love, much, mommy, know, right, amazing, woma...",0.280952
23825,Sat Sep 08 18:45:24 +0000 2018,mama needs a dictionary gracious humble u...,serena williams,"[mama, need, dictionary, gracious, humble, umm...",0.195238
23826,Sat Sep 08 18:45:23 +0000 2018,i would rather lose than cheat,serena williams,"[would, rather, lose, cheat]",0.000000
23827,Sat Sep 08 18:45:23 +0000 2018,sorry do not agree on this one referee had n...,serena williams,"[sorry, agree, one, referee, business, making,...",-0.250000

In [89]:
analyzed_tweets.sort_values(by="sentiment")

,tweet_date,tweet_text,search query,processed_tweet,sentiment
9067,Sat Sep 08 18:35:26 +0000 2018,no you are terribly disrespectful with shing...,naomi osaka,"[terribly, disrespectful, shingo, kunieda, yui...",-1.0
16528,Sat Sep 08 19:22:34 +0000 2018,yes after warning she had the penalty coach...,serena williams,"[yes, warning, penalty, coach, raquet, screami...",-1.0
12414,Sat Sep 08 19:52:02 +0000 2018,shame that disgraceful official did not show h...,serena williams,"[shame, disgraceful, official, show, level, re...",-1.0
4634,Sat Sep 08 19:07:53 +0000 2018,as opposed to carlos stealing a point how do...,naomi osaka,"[opposed, carlos, stealing, point, get, coachi...",-1.0
23102,Sat Sep 08 18:48:28 +0000 2018,he will forever be known as a horrible ref,serena williams,"[forever, known, horrible, ref]",-1.0
21940,Sat Sep 08 18:53:42 +0000 2018,mate you are quoting incidents from decades ag...,serena williams,"[mate, quoting, incident, decade, ago, abused,...",-1.0
19423,Sat Sep 08 19:05:31 +0000 2018,serena williams conduct tonight was disgusting...,serena williams,"[serena, williams, conduct, tonight, disgustin...",-1.0
16726,Sat Sep 08 19:21:12 +0000 2018,awful,serena williams,[awful],-1.0
16767,Sat Sep 08 19:20:56 +0000 2018,waoooo so serena is for tennis channel what hi...,serena williams,"[waoooo, serena, tennis, channel, hillary, cnn...",-1.0
19549,Sat Sep 08 19:04:56 +0000 2018,disgusting sportsmanship by serenawilliams u...,serena williams,"[disgusting, sportsmanship, serenawilliams, us...",-1.0
21872,Sat Sep 08 18:54:01 +0000 2018,embarrassing video just awfully inaccurate,serena williams,"[embarrassing, video, awfully, inaccurate]",-1.0
1274,Sat Sep 08 19:43:26 +0000 2018,terrible ref is the goat congrats to on ...,naomi osaka,"[terrible, ref, goat, congrats, well, deserved...",-1.0
1280,Sat Sep 08 19:43:23 +0000 2018,in the end you where a horrible example to you...,naomi osaka,"[end, horrible, example, daughter, congratulat...",-1.0
19293,Sat Sep 08 19:06:12 +0000 2018,you are thanking her for outrageous sportsmans...,serena williams,"[thanking, outrageous, sportsmanship]",-1.0
17300,Sat Sep 08 19:17:43 +0000 2018,why are you defending serenas bullying it was...,serena williams,"[defending, serenas, bullying, awful, truly, d...",-1.0
8347,Sat Sep 08 18:39:59 +0000 2018,selective call from the ump sexism at it is w...,naomi osaka,"[selective, call, ump, sexism, worst, robbed]",-1.0
1302,Sat Sep 08 19:43:06 +0000 2018,the crowd were disgusting and even serena kn...,naomi osaka,"[crowd, disgusting, even, serena, knew, told, ...",-1.0
8343,Sat Sep 08 18:40:00 +0000 2018,she deserved that my friend her coach just ...,naomi osaka,"[deserved, friend, coach, said, coaching, must...",-1.0
19289,Sat Sep 08 19:06:14 +0000 2018,did you watch the match she was the cause of ...,serena williams,"[watch, match, cause, booing, tantrum, disgrac...",-1.0
21822,Sat Sep 08 18:54:13 +0000 2018,so you must have willfully ignored the grace o...,serena williams,"[must, willfully, ignored, grace, serena, comf...",-1.0
23609,Sat Sep 08 18:46:19 +0000 2018,you are my champion today and always that c...,serena williams,"[champion, today, always, chair, awful]",-1.0
8479,Sat Sep 08 18:39:06 +0000 2018,including serena terrible behaviour,naomi osaka,"[including, serena, terrible, behaviour]",-1.0
10162,Sat Sep 08 18:29:50 +0000 2018,what an awful ending to the womens title match...,naomi osaka,"[awful, ending, woman, title, match, usopen, r...",-1.0
15729,Sat Sep 08 19:27:49 +0000 2018,yes because now you can pick and choose what ...,serena williams,"[yes, pick, choose, show, people, trying, cove...",-1.0
7041,Sat Sep 08 18:48:36 +0000 2018,fans were pathetic,naomi osaka,"[fan, pathetic]",-1.0
19776,Sat Sep 08 19:03:41 +0000 2018,was awful and her behavior was out of control,serena williams,"[awful, behavior, control]",-1.0
15856,Sat Sep 08 19:27:01 +0000 2018,talk about a pathetic straw man argument mcen...,serena williams,"[talk, pathetic, straw, man, argument, mcenroe...",-1.0
5087,Sat Sep 08 19:03:41 +0000 2018,was awful and her behavior was out of control,naomi osaka,"[awful, behavior, control]",-1.0
5072,Sat Sep 08 19:03:50 +0000 2018,heard serena in press conference trying to mak...,naomi osaka,"[heard, serena, press, conference, trying, mak...",-1.0
2581,Sat Sep 08 19:28:29 +0000 2018,agreed that had to be the moment of her life ...,naomi osaka,"[agreed, moment, life, people, booing, horrible]",-1.0
...,...,...,...,...,...
5549,Sat Sep 08 19:00:11 +0000 2018,naomi osaka you did best congratulation,naomi osaka,"[naomi, osaka, best, congratulation]",1.0
781,Sat Sep 08 19:49:48 +0000 2018,you are the best,naomi osaka,[best],1.0
16998,Sat Sep 08 19:19:27 +0000 2018,is still the worlds greatest living athlete ...,serena williams,"[still, world, greatest, living, athlete, one,...",1.0
5491,Sat Sep 08 19:00:37 +0000 2018,congrats sis played an excellent match,naomi osaka,"[congrats, si, played, excellent, match]",1.0
10947,Sat Sep 08 18:26:42 +0000 2018,yes seena should have restrained herself and ...,naomi osaka,"[yes, seena, restrained, none, would, happened...",1.0
19362,Sat Sep 08 19:05:48 +0000 2018,you will always always be named the best us...,serena williams,"[always, always, named, best, usopenfinal]",1.0
21391,Sat Sep 08 18:56:07 +0000 2018,serena williams is awesome,serena williams,"[serena, williams, awesome]",1.0
19355,Sat Sep 08 19:05:51 +0000 2018,she is the best,serena williams,[best],1.0
16009,Sat Sep 08 19:25:57 +0000 2018,serena williams is one of the greatest athlete...,serena williams,"[serena, williams, one, greatest, athlete, time]",1.0
4993,Sat Sep 08 19:04:34 +0000 2018,seems the greatest athlete ever lost to some...,naomi osaka,"[seems, greatest, athlete, ever, lost, someone...",1.0
8146,Sat Sep 08 18:41:17 +0000 2018,rt and you turn the best lawyers into ...,naomi osaka,"[rt, turn, best, lawyer, tennis, zombie, black...",1.0
18205,Sat Sep 08 19:12:29 +0000 2018,serena williams is the greatest womans tennis ...,serena williams,"[serena, williams, greatest, woman, tennis, pl...",1.0
10917,Sat Sep 08 18:26:49 +0000 2018,you are the best you should admire someone ...,naomi osaka,"[best, admire, someone, deserves, today, show,...",1.0
13521,Sat Sep 08 19:43:30 +0000 2018,you are awesome serena,serena williams,"[awesome, serena]",1.0
14429,Sat Sep 08 19:37:05 +0000 2018,you are going to want to watch a best if john...,serena williams,"[going, want, watch, best, john, mcenroe, reel...",1.0
9378,Sat Sep 08 18:33:42 +0000 2018,naomi osaka you are awesome usopen,naomi osaka,"[naomi, osaka, awesome, usopen]",1.0
16029,Sat Sep 08 19:25:48 +0000 2018,serena williams still the greatest athlete i h...,serena williams,"[serena, williams, still, greatest, athlete, s...",1.0
22453,Sat Sep 08 18:51:12 +0000 2018,serena williams is the greatest athlete of all...,serena williams,"[serena, williams, greatest, athlete, time, ba...",1.0
23413,Sat Sep 08 18:47:06 +0000 2018,will always be greatest tennis athlete in hi...,serena williams,"[always, greatest, tennis, athlete, history, e...",1.0
20308,Sat Sep 08 19:01:08 +0000 2018,yet another reason why serena williams may be ...,serena williams,"[yet, another, reason, serena, williams, may, ...",1.0
10930,Sat Sep 08 18:26:45 +0000 2018,got every decision perfectly correct man dese...,naomi osaka,"[got, every, decision, perfectly, correct, man...",1.0
6568,Sat Sep 08 18:52:04 +0000 2018,yes she was well on her way without the chair...,naomi osaka,"[yes, well, way, without, chair, feeling, need...",1.0
4968,Sat Sep 08 19:04:48 +0000 2018,and they played excellent tennis usopen,naomi osaka,"[played, excellent, tennis, usopen]",1.0
7176,Sat Sep 08 18:47:36 +0000 2018,nope naomi osaka is the best today,naomi osaka,"[nope, naomi, osaka, best, today]",1.0
10075,Sat Sep 08 18:30:11 +0000 2018,this espn interview with naomi osaka is deligh...,naomi osaka,"[espn, interview, naomi, osaka, delightful]",1.0
5986,Sat Sep 08 18:56:43 +0000 2018,this made me cry naomi played awesome,naomi osaka,"[made, cry, naomi, played, awesome]",1.0
22481,Sat Sep 08 18:51:02 +0000 2018,serena did an excellent job during the presser...,serena williams,"[serena, excellent, job, presser, also, woman,...",1.0
14468,Sat Sep 08 19:36:45 +0000 2018,wish she had been more gracious in losing toda...,serena williams,"[wish, gracious, losing, today, still, best, e...",1.0
6421,Sat Sep 08 18:53:19 +0000 2018,the greatest of all time are graf and navratil...,naomi osaka,"[greatest, time, graf, navratiliva]",1.0
21337,Sat Sep 08 18:56:21 +0000 2018,federer nadal murray etc etc etc have all ye...,serena williams,"[federer, nadal, murray, etc, etc, etc, yelled...",1.0

In [91]:
analyzed_tweets.groupby(by="search query").size()

search query
naomi osaka        11380
serena williams    12395
dtype: int64

In [92]:
naomi_analysis = analyzed_tweets[analyzed_tweets['search query'] == 'naomi osaka']

In [93]:
serena_analysis = analyzed_tweets[analyzed_tweets['search query'] == 'serena williams']

In [95]:
naomi_analysis['sentiment'].sum()

1897.4450200120045

In [96]:
serena_analysis['sentiment'].sum()

1305.5000090534168

I think I've got my final answer! By performing a crude count of the overall sentiment for each search query, I was able to determine that tweets for the search query 'naomi osaka' were on the whole more positive than tweets with the search query 'serena williams'. I wonder if I can perform a statistical analysis to prove this. I'm excited to move into visualizations so I can see this data more clearly.